apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-ui-example
spec:
  selector:
    matchLabels:
      app: starling-ui-example
  template:
    metadata:
      labels:
        app: starling-ui-example
    spec:
      hostNetwork: true
      shareProcessNamespace: true
      containers:
      - name: starling-ui-example
        image: uobflightlabstarling/starling-ui-example:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 9090
